apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-js-deployment
  namespace: nestjs
  labels:
    app: nest-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-js
  template:
    metadata:
      labels:
        app: nest-js
    spec:
      containers:
      - name: nest-js
        image: nestjs_kubernetes:2
        imagePullPolicy: IfNotPresent
        env: 
        - name: NODE_ENV
          value: "production"
        - name: environmentVar
          value: "production"
        - name: label
          value: "prodInstance"
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: nestjs-config