apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-js-deployment
  namespace: nestjs
  labels:
    app: nest-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-js
  template:
    metadata:
      labels:
        app: nest-js
    spec:
      containers:
      - name: nest-js
        image: nestjs_kubernetes:2
        imagePullPolicy: IfNotPresent
        env: 

        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nestjs-config # Name of your ConfigMap
              key: NODE_ENV # Key from the ConfigMap
        - name: environmentVar
          valueFrom:
            configMapKeyRef:
              name: nestjs-config # Name of your ConfigMap
              key: environmentVar # Key from the ConfigMap
        - name: label
          valueFrom:
            configMapKeyRef:
              name: nestjs-config # Name of your ConfigMap
              key: label # Key from the ConfigMap
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nestjs-config # Name of your ConfigMap
              key: PORT  # Key from the ConfigMap
        ports:
        - containerPort: 5000
        
            