apiVersion: v1
kind: Service
metadata:
  name: nest-service
  namespace: nestjs
spec:
  type: NodePort
  selector:
    app: nest-js
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30003